# Generated by Django 2.1.1 on 2018-09-20 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_del', models.DateTimeField()),
                ('vigencia_al', models.DateTimeField()),
                ('importe', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.Articulo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.Servicio')),
            ],
        ),
    ]
