# Generated by Django 2.1.1 on 2018-09-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('paterno', models.CharField(max_length=30)),
                ('materno', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('colonia', models.CharField(max_length=30)),
                ('cp', models.CharField(max_length=5)),
                ('estado', models.CharField(max_length=3)),
                ('tel_fijo', models.CharField(max_length=20)),
                ('tel_movil', models.CharField(max_length=20)),
                ('tel_trabajo', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=3)),
                ('sexo', models.CharField(max_length=2)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
