# Generated by Django 2.1.1 on 2018-10-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='materno',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(default='ACT', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel_fijo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel_movil',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel_trabajo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
