# Generated by Django 2.1.1 on 2018-10-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20181027_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
