# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.TextField()),
                ('fecha_termino', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField()),
                ('descuento', models.IntegerField()),
                ('servicio', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('persona_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.AddField(
            model_name='nota',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notas.Status'),
        ),
    ]
