# Generated by Django 2.1.1 on 2018-10-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='pagado',
            field=models.IntegerField(default=0),
        ),
    ]
