# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='folio',
        ),
    ]
