# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20180524_1815'),
        ('notas', '0002_remove_nota_folio'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalleNota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo')),
                ('nota', models.ForeignKey(db_column='nota_id', on_delete=django.db.models.deletion.CASCADE, to='notas.Nota')),
            ],
        ),
    ]
