# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_auto_20180619_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='nota',
            field=models.ForeignKey(db_column='nota_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='notas.Nota'),
        ),
    ]
