# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_auto_20180620_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='servicio',
        ),
        migrations.AlterField(
            model_name='nota',
            name='descuento',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='observaciones',
            field=models.TextField(null=True),
        ),
    ]
