# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_auto_20180704_1913'),
        ('empleados', '0003_auto_20180704_1913'),
        ('notas', '0006_auto_20180627_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='persona_servicio',
            new_name='empleado',
        ),
        migrations.AlterField(
            model_name='nota',
            name='status',
            field=models.CharField(default='NVO', max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
