# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0007_auto_20180704_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='status',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
