# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0009_auto_20180707_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='empleados.Empleado'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='fecha_termino',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='status',
            field=models.CharField(default='NVA', max_length=3),
        ),
    ]
