# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0010_auto_20180710_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='empleados.Empleado'),
        ),
    ]
