# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_auto_20180704_1913'),
        ('servicios', '0001_initial'),
        ('notas', '0011_auto_20180710_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo')),
                ('detalle', models.ForeignKey(db_column='detalle_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='notas.Detalle')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Servicio')),
            ],
        ),
    ]
