# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_auto_20180704_1913'),
        ('servicios', '0001_initial'),
        ('notas', '0012_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo')),
                ('detalle', models.ForeignKey(db_column='detalle_id', on_delete=django.db.models.deletion.CASCADE, related_name='serviciodetalle', to='notas.Detalle')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.AddField(
            model_name='serviciodetalle',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Servicio'),
        ),
    ]
