# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('notas', '0013_auto_20180727_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciodetalle',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='serviciodetalle',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='serviciodetalle',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='partida',
        ),
        migrations.AddField(
            model_name='detalle',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.Servicio'),
        ),
        migrations.DeleteModel(
            name='ServicioDetalle',
        ),
    ]
