# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-23 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0015_detalle_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='precio_unitario',
            field=models.IntegerField(null=True),
        ),
    ]
