# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_auto_20180704_1913'),
        ('servicios', '0001_initial'),
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_del', models.DateTimeField()),
                ('vigencia_al', models.DateTimeField()),
                ('importe', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo')),
            ],
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.AddField(
            model_name='precio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Servicio'),
        ),
    ]
