# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20180524_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticuloClasif',
            new_name='Clasificacion',
        ),
    ]
