# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20180616_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificacion',
            name='status',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='clasificacion',
        ),
        migrations.DeleteModel(
            name='Clasificacion',
        ),
    ]
