# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_auto_20180616_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='status',
            field=models.CharField(default='NVO', max_length=3),
            preserve_default=False,
        ),
    ]
