# Generated by Django 2.1.1 on 2018-10-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20181028_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='nombre_corto',
            field=models.CharField(default='prueba', max_length=8),
            preserve_default=False,
        ),
    ]
