# Generated by Django 2.1.1 on 2018-10-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descripcion_corta',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
