# Generated by Django 2.1.1 on 2018-09-20 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        ('empleados', '0001_initial'),
        ('servicios', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField(null=True)),
                ('precio_unitario', models.IntegerField(null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.TextField(null=True)),
                ('status', models.CharField(default='NVA', max_length=3)),
                ('fecha_termino', models.DateTimeField(null=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('descuento', models.IntegerField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleado', to='empleados.Empleado')),
            ],
        ),
        migrations.AddField(
            model_name='detalle',
            name='nota',
            field=models.ForeignKey(db_column='nota_id', on_delete=django.db.models.deletion.PROTECT, related_name='detalle', to='notas.Nota'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='servicios.Servicio'),
        ),
    ]
