# Generated by Django 2.1.1 on 2018-10-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_nota_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='precio_unitario',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='descuento',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='pagado',
            field=models.FloatField(default=0),
        ),
    ]
